defaults: &defaults
  facebook:
    api_key: "726393000750444"
    api_secret: "3a202f98dafc5761dc47ca5e6fa167e4"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  facebook:
    api_key: "723155264407551"
    api_secret: "e4723505792fcb9db4c4fa1e6e15b767"